### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zhongwen-4** [Onimaimai/nonebot-plugin-buy#1]
需要在导入nonebot_plugin_apscheduler插件前require("nonebot_plugin_apscheduler")

**Comment by zhongwen-4** [comment]
建议参考https://nonebot.dev/docs/best-practice/scheduler#%E5%AF%BC%E5%85%A5%E8%B0%83%E5%BA%A6%E5%99%A8

**Comment by Onimaimai** [comment]
谢谢
